apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: blogpostmanagementwebapi
    annotations:
        kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: blogpostmanagementwebapi
          servicePort: 80
