apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: blogpostmanagementwebapi
    annotations:
        kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - host: blog-post-management.polandcentral.cloudapp.azure.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
              name: blogpostmanagementwebapi
              port:
                  number: 80
